USE [master]
GO

/****** Object:  Database [BDCarla]    Script Date: 04/05/2024 18:06:48 ******/
CREATE DATABASE [BDCarla]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BDCarla', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BDCarla.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BDCarla_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BDCarla_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BDCarla].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BDCarla] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BDCarla] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BDCarla] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BDCarla] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BDCarla] SET ARITHABORT OFF 
GO

ALTER DATABASE [BDCarla] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BDCarla] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BDCarla] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BDCarla] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BDCarla] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BDCarla] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BDCarla] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BDCarla] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BDCarla] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BDCarla] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BDCarla] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BDCarla] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BDCarla] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BDCarla] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BDCarla] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BDCarla] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BDCarla] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BDCarla] SET RECOVERY FULL 
GO

ALTER DATABASE [BDCarla] SET  MULTI_USER 
GO

ALTER DATABASE [BDCarla] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BDCarla] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BDCarla] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BDCarla] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BDCarla] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BDCarla] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BDCarla] SET QUERY_STORE = ON
GO

ALTER DATABASE [BDCarla] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [BDCarla] SET  READ_WRITE 
GO

