//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPregunta4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaccionbancaria
    {
        public int id_Transaccion { get; set; }
        public Nullable<int> cuentaID { get; set; }
        public string tipoTransaccion { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<System.DateTime> fechaHora { get; set; }
    }
}
